services:
  orders.api:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: Services/Orders/Orders.API/Dockerfile
  notifications.api:
    image: ${DOCKER_REGISTRY-}notificationsapi
    build:
      context: .
      dockerfile: Services/Notifications/Notifications.API/Dockerfile
  messagebroker:
     image: rabbitmq:management
